import Head from 'next/head'
import styled from 'styled-components'
import Header from '../components/Header/Header'
import Styles from './index.styles'

export const Container = styled.div`${Styles.container}`

// export const Title = styled.h1`font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;`



export default function Home() {
  return (
    <div>
      <Head>
        <title>DinamizaThor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Container>
        <Header />
      </Container>
    </div>
  )
}
